In [112]:
import pandas as pd
import numpy as np

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Perceptron

In [42]:
df = pd.read_csv("cleaned.csv").iloc[:,1:].drop(columns=["kills","deaths"])

In [43]:
df = pd.get_dummies(df)

In [44]:
df.head()

,gamelength,result,assists,teamkills,teamdeaths,firstblood,team kpm,ckpm,elders,opp_elders,...,teamname_Evil Geniuses,teamname_Fnatic,teamname_G2 Esports,teamname_GAM Esports,teamname_Gen.G,teamname_JD Gaming,teamname_Rogue,teamname_Royal Never Give Up,teamname_T1,teamname_Top Esports
0,1786,1,64,24,14,1.0,0.8063,1.2766,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
1,2213,1,48,18,11,0.0,0.4880,0.7863,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
2,2080,1,36,15,15,0.0,0.4327,0.8654,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
3,1504,1,28,17,6,1.0,0.6782,0.9176,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
4,1692,1,38,17,10,0.0,0.6028,0.9574,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0

In [45]:
y = df["result"]
X = df.drop(columns = ["result"])
X

,gamelength,assists,teamkills,teamdeaths,firstblood,team kpm,ckpm,elders,opp_elders,firstherald,...,teamname_Evil Geniuses,teamname_Fnatic,teamname_G2 Esports,teamname_GAM Esports,teamname_Gen.G,teamname_JD Gaming,teamname_Rogue,teamname_Royal Never Give Up,teamname_T1,teamname_Top Esports
0,1786,64,24,14,1.0,0.8063,1.2766,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
1,2213,48,18,11,0.0,0.4880,0.7863,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
2,2080,36,15,15,0.0,0.4327,0.8654,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
3,1504,28,17,6,1.0,0.6782,0.9176,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
4,1692,38,17,10,0.0,0.6028,0.9574,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,1654,5,2,19,0.0,0.0726,0.7618,0.0,0.0,1.0,...,1,0,0,0,0,0,0,0,0,0
1245,1768,15,8,12,0.0,0.2715,0.6787,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
1246,1950,33,15,3,1.0,0.4615,0.5231,0.0,0.0,1.0,...,1,0,0,0,0,0,0,0,0,0
1247,1504,10,6,17,0.0,0.2394,0.9176,0.0,0.0,1.0,...,1,0,0,0,0,0,0,0,0,0
1248,1687,16,8,21,1.0,0.2845,1.0314,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [51]:
param_grid = {'solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]}
clf = GridSearchCV(LogisticRegression(), param_grid, n_jobs= -1)
clf.fit(X_train,y_train)
print("Best estimator found by grid search:")
print(clf.best_estimator_)

Best estimator found by grid search:
LogisticRegression(solver='newton-cg')

/home/yuzhoufa/.local/lib/python3.8/site-packages/sklearn/utils/optimize.py:210: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn(

In [72]:
print("The training error is:",1-clf.score(X_train, y_train))
print("The test error is:",1 -clf.score(X_test, y_test))

The training error is: 0.0
The test error is: 0.03194888178913735

In [87]:
ypred = clf.predict_proba(X)
ypred[::,1]

array([9.99999839e-01, 9.99999677e-01, 9.99972665e-01, ...,
       1.00000000e+00, 1.46389436e-14, 4.99590023e-15])

In [92]:
df2 = pd.read_csv("cleaned.csv").iloc[:,1:]

In [110]:
df2["win_ratio"] = ypred[::,1]* 100
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [120]:
df2

,side,teamname,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,firstblood,...,opp_towers,damagetochampions,dpm,damagetakenperminute,totalgold,earnedgold,earned gpm,goldspent,gspd,win_ratio
0,Blue,JD Gaming,1786,1,24,14,64,24,14,1.000,...,2.000,66630.000,2238.410,2817.010,60517,40922.000,1374.759,54700.000,0.149,100.000
1,Red,JD Gaming,2213,1,18,11,48,18,11,0.000,...,4.000,79332.000,2150.890,2628.098,70689,46738.000,1267.185,64135.000,0.063,100.000
2,Blue,JD Gaming,2080,1,15,15,36,15,15,0.000,...,4.000,92313.000,2662.875,2553.952,64503,41909.000,1208.914,55725.000,-0.077,99.997
3,Red,JD Gaming,1504,1,17,6,28,17,6,1.000,...,1.000,74476.000,2971.117,2823.590,55898,39179.000,1562.992,47585.000,0.252,100.000
4,Red,JD Gaming,1692,1,17,10,38,17,10,0.000,...,2.000,75775.000,2687.057,2952.340,60278,41642.000,1476.667,50450.000,0.096,100.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,Blue,Evil Geniuses,1654,0,2,19,5,2,19,0.000,...,9.000,55053.000,1997.086,3318.428,42635,24386.000,884.619,40475.000,-0.094,0.000
1245,Red,Evil Geniuses,1768,0,8,12,15,8,12,0.000,...,7.000,40835.000,1385.803,3043.778,47488,28076.000,952.805,45183.000,-0.064,0.000
1246,Red,Evil Geniuses,1950,1,15,3,33,15,3,1.000,...,1.000,66734.000,2053.354,2587.631,64343,43075.000,1325.385,55608.000,0.187,100.000
1247,Blue,Evil Geniuses,1504,0,6,17,10,6,17,0.000,...,11.000,43815.000,1747.939,3777.886,37765,21046.000,839.601,36920.000,-0.252,0.000
1248,Blue,Evil Geniuses,1687,0,8,21,16,8,21,1.000,...,11.000,61025.000,2170.421,3347.836,44522,25937.000,922.478,42800.000,-0.188,0.000

In [114]:
param_grid = {'alpha': [0.00005,0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}
clf1 = GridSearchCV(Perceptron(random_state=0), param_grid, n_jobs= -1)
clf1.fit(X_train,y_train)
print("Best estimator found by grid search:")
print(clf1.best_estimator_)

Best estimator found by grid search:
Perceptron(alpha=5e-05)

In [115]:
print("The training error is:",1-clf1.score(X_train, y_train))
print("The test error is:",1 -clf1.score(X_test, y_test))

The training error is: 0.05128205128205132
The test error is: 0.09584664536741216

In [119]:
mean_squared_error(clf1.predict(X),y)

0.06244995996797438

In [146]:
win_dict = {}
for i in np.unique(df2.teamname.values):
    win_dict[i] = sum(df2[df2['teamname'] == i].win_ratio>90)/len(df2[df2['teamname'] == i].win_ratio)
win_dict

{'100 Thieves': 0.5657894736842105,
 'CTBC Flying Oyster': 0.68,
 'Cloud9': 0.5769230769230769,
 'DRX': 0.5317460317460317,
 'DWG KIA': 0.5982905982905983,
 'EDward Gaming': 0.45454545454545453,
 'Evil Geniuses': 0.6178861788617886,
 'Fnatic': 0.5526315789473685,
 'G2 Esports': 0.6292134831460674,
 'GAM Esports': 0.7159090909090909,
 'Gen.G': 0.7321428571428571,
 'JD Gaming': 0.7142857142857143,
 'Rogue': 0.6027397260273972,
 'Royal Never Give Up': 0.7391304347826086,
 'T1': 0.7553956834532374,
 'Top Esports': 0.5}

**Data is linearly separable since the perceptron model converges, we can see that both models have pretty good accuracy if the stats are given.**